### PR TITLE
Use defaults from profileNamespace in color macros

### PR DESCRIPTION
**Pull request by 654wak654**
Zeus seems to be the only editor that respects these values. 3DEN and Mars use their own static values. For someone like me who uses the Takistan-2012 color preset this stuff important for consistency.

There is also a set of background and text color macros in `profileNamespace`:
```
igui_bcg_rgb_r
igui_bcg_rgb_g
igui_bcg_rgb_b
igui_bcg_rgb_a

igui_text_rgb_r
igui_text_rgb_g
igui_text_rgb_b
igui_text_rgb_a
```
Didn't use them since I don't know which one is `COLOR_ACTIVE_X` and which one is `COLOR_DEFAULT_X`

### CODE REVIEW

**Comment by jameslkingsley** [comment]
Really there needs to be two macros for each side colour. Like what [these do](https://github.com/654wak654/mars/blob/2bc595301dfbe7d0eed21e6c1649144cb41383f6/addons/main/script_macros.hpp#L183-L194). That way you can use them in a config as well.

**Comment by 654wak654** [comment]
So duplicate all of them with `QUOTE()` and add a `_S` at the end?

**Comment by jameslkingsley** [comment]
Yeah

**Comment by 654wak654** [comment]
`_S` stands for script and not string?

**Comment by jameslkingsley** [comment]
Yeah... it was late

**Pull request closed without merging**
